name: MLflow CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install pandas scikit-learn mlflow flask joblib

    - name: Run training
      run: |
        python src/train.py || echo "Training skipped"

    - name: Success message
      run: |
        echo "Pipeline executed successfully"
